HOST: http://www.example.com

--- Togglity API Blueprint v1 ---
---
Description TBD.
---

--
Application Feature Toggle Resources
The following is a section of resources exposed by a togglified application. 
--
Identify the application.
GET /{application}
< 200
< Content-Type: application/json
{ "application": "application name here" }

Lists feature toggles exposed by the application.
GET /{application}/toggles
< 200
< Content-Type: application/json
{ "toggles": [
    { "myfeature": true, "url": "/{application}/toggles/myfeature" },
    { "featureX": false, "url": "/{application}/toggles/featureX" },
    { "a_feature": true, "url": "/{application}/toggles/a_feature" },
] }

Get a feature toggle.
GET /{application}/toggles/{feature}
< 200
< Content-Type: application/json
{ "myfeature": true }

Set a feature toggle.
PUT /{application}/toggles/{feature}
> Content-Type: application/json
{ "myfeature": false }
< 200
< Content-Type: application/json
{ "status": "updated", "url": "/toggles/myfeature" }
+++++
< 201
< Content-Type: application/json
{ "status": "created", "url": "/toggles/myfeature" }
+++++
< 404
{ "No such toggle"  }